# Site settings
title: CodingBlog
url: "https://kinshines.github.io"
baseurl: "https://kinshines.github.io"
#timezone: Asia/Shanghai
description: 王超宇的个人博客网站，前端HTML、HTML5、CSS、CSS3、JavaScript、JQuery，后端asp.net等编程经验总结分享。
# Your information
email: chaoyuweb@gmail.com
author: Chaoyu
place: Qingdao
domain: Internet
company: Haimawan.com
position: .net developer
school: Qingdao University
major: Electrical & Information Engineering
resume: "https://kinshines.github.io/cv"
profile: 无善无恶心之体</br>有善有恶意之动</br>知善知恶是良知</br>为善去恶是格物
signature: 私、失敗しないので。
twitter_username: chaoyuweb
weibo_username:  chaoyuweb
github_username:  kinshines
linkedin_username: wangchaoyu

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#  duoshuo_shortname: kinshines 
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
