# Site settings
title: 朝花夕拾
url: "https://kinshines.github.io"
baseurl: "/"
#timezone: Asia/Shanghai
#description: 王超宇的个人博客网站，前端HTML、HTML5、CSS、CSS3、JavaScript、JQuery，后端asp.net等编程经验总结分享。
# Your information
email: chaoyuweb@gmail.com
author: kinshines
place: 青岛
domain: 互联网
company: 海马玩
position: ".net开发"
school: 青岛大学
major: 电子信息工程
resume: "https://kinshines.github.io/cv"
profile: 无善无恶心之体，有善有恶意之动，知善知恶是良知，为善去恶是格物。
twitter_username: chaoyuweb
weibo_username: chaoyuweb
github_username: kinshines

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
 duoshuo_shortname: kinshines
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
